# Generated by Django 4.1.5 on 2023-03-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
