# Generated by Django 4.1.5 on 2023-03-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0002_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Boys',
        ),
        migrations.AlterModelTable(
            name='boys',
            table='boys',
        ),
    ]
